# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |testing|
  testing.vm.box = "geerlingguy/centos7"
  testing.vm.hostname = "elastic"
  testing.vm.network "private_network", ip: "10.20.188.253"
  testing.vm.network "forwarded_port", guest: 80, host: 8080
  testing.vm.provider "virtualbox" do |testing|
      testing.customize [ "modifyvm", :id, "--cpus", "1" ]
      testing.customize [ "modifyvm", :id, "--memory", "512" ]
  end
end
